const LabWeek2023LibP2P01 = "2023-labweek-libp2p-01.png";
const Vienna2023Svelte = "2023-vienna-svelte-02.png";
const Thailand2022OrbitDB = "2022-thailand-orbitdb-04.png";
const CoworkingGoaSunsetMediation01 = "coworking-goa-sunset-mediation-01.png";
const Mallorca2012Loft38Portixol01 = "2012-LOFT38-01.png";
const BitcoinCore01 = "bitcoin-core-01.png";
const KarakorumWorking01 = "karakorum-working-01.png";
const CoworkingLeipzig01 = "coworking-leipzig-01.png";
const LeipzigWaldstrasseGrails01 = "2009-leipzig-waldstrasse-grails-01.png";
const VsaJump07 = "vsa-jump-07.png";
export let timeline_en = [
    { image: LabWeek2023LibP2P01, slug:"labweek23", year: "2023", headline: "Local First Software & Peer-To-Peer Development", industry:"Blockchain / Peer-To-Peer", location: "Istanbul, Republic of Türkiye", projects: 'Attending Labweek23 Conference, LibP2P day, IPFSConnect', technologies: 'P2PLib, IPFS, Helia'},
    { image: Vienna2023Svelte, slug:"vienna-svelte", year: "2023", headline: "Svelte/SvelteKit Development", industry:"Pharmaceutical Industry",  location: "Vienna, Republic of Austria", projects: 'Svelte web app for a scientific research platform', technologies: 'Svelte/SvelteKit 4.0, JavaScript, Cypress, Playwright, JSDoc'},
    { image: Thailand2022OrbitDB, slug:"orbitdb-blog", year: "2022", headline: "OrbitDB, LibP2P, JS-IPFS / Helia",  industry:"Blockchain / Peer-To-Peer Development / IT / Media",  location: "Kingdom of Thailand, Malaysia, Lao People's Democratic Republic", projects: 'Decentralized Peer-to-Peer Blog', technologies: 'ReactJS, JavaScript, Cypress, OrbitDB, libp2p, js-ipfs, NodeJS,'},
    { image: CoworkingGoaSunsetMediation01, slug:"remote-yoga", year:"2013-2016", headline: "Remote.Yoga Startup \"Akashionata\"", industry:"Health", location: "Agonda, Goa, Republic Indien", projects:"Video & audio educational platform for yoga students and yoga teacher (mobile & web)", technologies: "MeteorJS, WebRTC, Apache-Cordoba, React-Native, Android, iOS"},
    { image: Mallorca2012Loft38Portixol01, slug:"mallorca-loft38", year:"2012", headline: "Java Swing & Google WebToolkit Development", industry:"Finance", location: "Palma de Mallorca, Spain", projects:"Porting a Java Swing Application to Google WebToolkit", technologies: "Google Web Toolkit, Java Swing, Android, iOS, Eclipse"},
    { image: BitcoinCore01, slug:"bitcoin-2011", year: "2011", headline: "The Bitcoin Principles", industry:"Crypto Currencies, Blockchain", location: "Rishikesh, Uttarakhand, Republic of India", projects: 'The Bitcoin Principles', technologies: 'The Bitcoin Principles, Bitcoin Core'},
    { image: KarakorumWorking01, slug:"karakorum", year: "2011", headline: "Travelling The Silk Road", industry:"Sabbatical",  location: "Karakoram Highway China/Islamic Republic of Pakistan", projects: 'Studies of world history, Gaining Cultural Competence', technologies: 'humility & openness'},
    { image: CoworkingLeipzig01, slug:"coworking-leipzig", year: "2009", headline: "Launching Le Space (beta) Coworking zu Leipzig", industry:"office rental / marketing / networking / education", location: "Leipzig, Germany", projects: 'Launching a Coworking Space, Co-Organizing Coworking Week Germany (2010), Joining 1st Coworking Europe Conference (2010)', technologies: 'Coworking, Bar Camps, Events'},
    { image: LeipzigWaldstrasseGrails01, slug:"leipzig-grails", year: "2009", headline: "Groovy & Grails Development",  industry:"IT", location:"Waldstraße Leipzig, Germany",  projects: "Implementing an open source technician report web app", technologies: "Groovy & Grails, Selenium, Eclipse"},
    { image: VsaJump07, slug:"vsa-jump", year: "2006", headline: "Java/J2EE & Java Swing Development", industry:"health / medical", location: "Munich/Gefrees, Germany", projects: 'Jump CRM/ERP for Pharmacies', technologies: 'Java/J2EE, Java Swing, SQL, Oracle DB'},
];

export const timeline_de = [
    { image: LabWeek2023LibP2P01, slug:"labweek23", year: "2023", headline: "Local First Software & Peer-To-Peer-Entwicklung", industry:"Blockchain / Peer-To-Peer", location: "Istanbul, Republik Türkei", projects: 'Labweek23-Konferenz, LibP2P-Tag, IPFSConnect u.v.a', technologies: 'P2PLib, IPFS, Helia'},
    { image: Vienna2023Svelte, slug:"vienna-svelte", year: "2023", headline: "Svelte/SvelteKit-Entwicklung", industry:"Pharmaindustrie",  location: "Wien, Republik Österreich", projects: 'Svelte Web-App für eine wissenschaftliche Plattform', technologies: 'Svelte/SvelteKit 4.0, JavaScript, Cypress, Playwright, JSDoc'},
    { image: Thailand2022OrbitDB, slug:"orbitdb-blog", year: "2022", headline: "OrbitDB, LibP2P, JS-IPFS / Helia",  industry:"Blockchain / Peer-To-Peer-Entwicklung / IT / Medien",  location: "Königreich Thailand, Malaysia, Demokratische Volksrepublik Laos", projects: 'Dezentraler Peer-to-Peer-Blog', technologies: 'ReactJS, JavaScript, Cypress, OrbitDB, libp2p, js-ipfs, NodeJS,'},
    { image: CoworkingGoaSunsetMediation01 , slug:"remote-yoga", year:"2013-2016", headline: "Remote.Yoga Startup \"Akashionata\"", industry:"Health", location: "Agonda, Goa, Republik Indien", projects:"Video/Audio Bildungsplattform für Yogalehrer und Yogaschüler (Mobile & Web)", technologies: "MeteorJS, WebRTC, Apache-Cordoba, React-Native, Android, iOS"},
    { image: Mallorca2012Loft38Portixol01 , slug:"mallorca-loft38", year:"2012", headline: "Java Swing & Google WebToolkit-Entwicklung", industry:"Finanzindustrie / Fond management", location: "Palma de Mallorca, Spanien", projects:"Portierung einer Java Swing-Anwendung auf Google WebToolkit", technologies: "Google Web Toolkit, Java Swing, Android, iOS, Eclipse"},
    { image: BitcoinCore01, slug:"bitcoin-2011", year: "2011", headline: "Die Bitcoin-Prinzipien", industry:"Kryptowährungen, Blockchain", location: "Rishikesh, Uttarakhand, Republik Indien", projects: 'Die Bitcoin-Prinzipien', technologies: 'Die Bitcoin-Prinzipien, Bitcoin Core'},
    { image: KarakorumWorking01, slug:"karakorum", year: "2011", headline: "Reality-Check Seidenstraße", industry:"Firmen-Sabbatical",  location: "Karakorum Highway, China/Islamische Republik Pakistan", projects: 'Selbststudium Weltgeschichte, Interkulturelle Kompetenz', technologies: 'Offenheit, Toleranz, Orientierungssinn'},
    { image: CoworkingLeipzig01, slug:"coworking-leipzig", year: "2009", headline: "Eröffnung Le Space (beta) Coworking zu Leipzig", industry:"Vermietung / Marketing / Netzwerk / Bildung", location: "Leipzig, Deutschland", projects: 'Gründung eines Coworking Space, Mitorganisation der Coworking Week Germany (2010), Teilnahme an der 1. Coworking Europe Conference in Brüssel (2010)', technologies: 'Coworking, Bar Camps, Events'},
    { image: LeipzigWaldstrasseGrails01, slug:"leipzig-grails", year: "2009", headline: "Groovy & Grails Entwicklung", industry:"IT", location:"Waldstraße Leipzig", projects: "Implementierung 'Technikerbericht' (Open Source) ", technologies: "Groovy & Grails, Selenium, Eclipse"},
    { image: VsaJump07, slug:"vsa-jump", year: "2006", headline: "Java/J2EE & Java Swing Entwicklung", industry:"Gesundheit / Medizin", location: "München/Gefrees, Deutschland", projects: 'Jump CRM/ERP für Apotheken', technologies: 'Java/J2EE, Java Swing, SQL, Oracle DB'},
];
