export const icons = {
    libp2p: {icon:"libp2p", url: "https://libp2p.io/"},
    helia: {icon:"helia.png", url: "https://helia.io/"},
    ipfs: {icon:"ipfs", url: "https://ipfs.io/"},
    svelte: {icon:"svelte", url: "https://svelte.dev/"},
    typescript: {icon:"typescript", url: "https://www.typescriptlang.org/"},
    javascript: {icon: "javascript", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript"},
    cypress: {icon:"cypress", url: "https://www.cypress.io/"},
    coffeescript: {icon:"coffeescript", url: "https://coffeescript.org/"},
    intellijidea: {icon:"intellijidea", url: "https://www.jetbrains.com/idea/"},
    react: {icon:"react", url: "https://reactjs.org/"},
    nginx: {icon:"nginx", url: "https://docs.nginx.com/"},
    nodedotjs: {icon:"nodedotjs", url: "https://nodejs.org/en/"},
    metamask: {icon:"metamask.png",url:"https://metamask.io"},
    docker: {icon:"docker", url: "https://www.docker.com/"},
    web3dotjs: {icon:"web3dotjs", url: "https://web3js.org/"},
    letsencrypt: {icon:"letsencrypt", url: "https://www.letsencrypt.org/"},
    openssl: {icon:"openssl", url: "https://www.openssl.org/"},
    webrtc: {icon:"webrtc", url: "https://webrtc.org/"},
    android: {icon:"android.png", url:"https://www.android.com/"},
    ios: {icon:"ios.png", url:"https://www.apple.com/ios"},
    meteor: {icon:"meteor", url: "https://www.meteor.com/"},
    apachecordova: {icon:"apachecordova", url: "https://cordova.apache.org/"},
    gwt: {icon:"gwt.png", url: "https://www.gwtproject.org/"},
    java: {icon:"java", url: "https://www.java.com/"},
    oracle: {icon:"oracle", url: "https://www.oracle.com/index.html"},
    eclipseide: {icon:"eclipseide", url: "https://www.eclipse.org/ide/"},
    bitcoin: {icon:"bitcoin", url: "https://bitcoin.org/"},
    grails: {icon:"grails", url: "https://grails.org/"},
    apachegroovy: {icon:"apachegroovy", url: "https://groovy-lang.org/"},
    mongodb: {icon:"mongodb", url: "https://www.mongodb.com/"},
    selenium: {icon:"selenium", url:"https://www.selenium.dev/"},
    nusrat: { icon: "nusrat-fateh-ali-khan.jpg", url: "https://youtu.be/d7AqPH-LgmI"},
    mdr: {icon:"mdr.png",url:"https://www.mdr.de/tv/"},
    mdrinfo: {icon:"mdr-info",url:"https://www.mdr.de/mdr-aktuell-nachrichtenradio"},
    kreuzer: {icon:"kreuzer-leipzig.jpg",url:"https://kreuzer-leipzig.de/"},
    lvz: {icon:"lvz.jpg",url:"https://www.lvz.de"},
    dnn: {icon:"dnn.jpg",url:"https://www.dnn.de/"},
    mysql: {icon:"mysql", url:"https://www.mysql.com/"}
};